<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="FB_ButtonToggle" Id="{cd045b62-cdd8-44e2-8806-19439e36e62d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_ButtonToggle
VAR_INPUT
	bReset  :BOOL;
	bEnable :BOOL := TRUE;
	bButt   :BOOL;
END_VAR
VAR
	fbButt  :R_TRIG;
END_VAR
VAR_OUTPUT
	bOutB   :BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbButt(CLK:=bButt);

IF fbButt.Q AND bEnable THEN
	IF bOutB THEN bOutB := FALSE;
		ELSE bOutB := TRUE;
	END_IF
END_IF

IF bReset THEN bOutB := FALSE;
END_IF]]></ST>
    </Implementation>
    <LineIds Name="FB_ButtonToggle">
      <LineId Id="3" Count="8" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>